TT/protected/controllers/AjaxController.php
<?php
/**
 * Project: yiiim
 * File: AjaxController.php
 * User: 明心
 * Date: 14-8-10
 * Time: 下午11:07
 * Desc: 
 */
class AjaxController extends Controller{

    public function actionLogin(){

        $result['status'] = false;
        $result['msg'] = '登录失败';
        $result['url'] = '/user/add';
        $adminInfo = Yii::app()->cache->get('cache_admininfo');
        if(!$adminInfo){
            $this->getAdminCache();
        }
        $admin['uname'] = $adminInfo[0]['uname'];
        $admin['pwd'] = $adminInfo[0]['pwd'];
        $uname = trim(Yii::app()->request->getPost('uname'));
        $pwd = md5(trim(Yii::app()->request->getPost('pwd')));
        if($admin['uname'] == $uname && $admin['pwd'] == $pwd){
            $result['status'] = true;
            $result['msg'] = '登录成功';
            Yii::app()->session['uname'] = $admin['uname'];
        }
        echo json_encode($result);
    }
}

TT/protected/controllers/SiteController.php
<?php
/**
 * 默认主页
 */
class SiteController extends Controller
{
	public $layout='column1';


    /**
     * 首页
     */
    public function actionIndex(){


        //$this->redirect('login');

	}

    /**
     * 登陆页面
     */
    public function actionLogin(){

        $this->render('login',array());

    }

    /**
     * 登出
     */
    public function actionLoginOut(){
        Yii::app()->session->clear();  //删除session变量
        Yii::app()->session->destroy(); //删除服务器的session信息
        $this->redirect('/login');
    }

    /**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
	    if($error=Yii::app()->errorHandler->error)
	    {
	    	if(Yii::app()->request->isAjaxRequest)
	    		echo $error['message'];
	    	else
	        	$this->render('error', $error);
	    }
	}


}

TT/protected/views/site/add.php
<?php
/**
 * Project: yiiim
 * File: add.php
 * User: 明心
 * Date: 14-8-4
 * Time: 下午5:15
 * Desc: 
 */ 

TT/protected/views/site/contact.php
<?php
$this->pageTitle=Yii::app()->name . ' - Contact Us';
$this->breadcrumbs=array(
    'Contact',
);
?>

    <h1>Contact Us</h1>

<?php if(Yii::app()->user->hasFlash('contact')): ?>

    <div class="flash-success">
        <?php echo Yii::app()->user->getFlash('contact'); ?>
    </div>

<?php else: ?>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="form">

        <?php $form=$this->beginWidget('CActiveForm'); ?>

        <p class="note">Fields with <span class="required">*</span> are required.</p>

        <?php echo $form->errorSummary($model); ?>

        <div class="row">
            <?php echo $form->labelEx($model,'name'); ?>
            <?php echo $form->textField($model,'name'); ?>
        </div>

        <div class="row">
            <?php echo $form->labelEx($model,'email'); ?>
            <?php echo $form->textField($model,'email'); ?>
        </div>

        <div class="row">
            <?php echo $form->labelEx($model,'subject'); ?>
            <?php echo $form->textField($model,'subject',array('size'=>60,'maxlength'=>128)); ?>
        </div>

        <div class="row">
            <?php echo $form->labelEx($model,'body'); ?>
            <?php echo $form->textArea($model,'body',array('rows'=>6, 'cols'=>50)); ?>
        </div>

        <?php if(CCaptcha::checkRequirements()): ?>
            <div class="row">
                <?php echo $form->labelEx($model,'verifyCode'); ?>
                <div>
                    <?php $this->widget('CCaptcha'); ?>
                    <?php echo $form->textField($model,'verifyCode'); ?>
                </div>
                <div class="hint">Please enter the letters as they are shown in the image above.
                    <br/>Letters are not case-sensitive.</div>
            </div>
        <?php endif; ?>

        <div class="row submit">
            <?php echo CHtml::submitButton('Submit'); ?>
        </div>

        <?php $this->endWidget(); ?>

    </div><!-- form -->

<?php endif; ?>

TT/protected/views/site/error.php
<?php
$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2>Error <?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

TT/protected/views/site/login.php
<!DOCTYPE html>
<html><head><meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <title>Delighted</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Styles -->
    <link href="/css/lock.css" rel="stylesheet">
    <link href="/css/animate.css" rel="stylesheet">
    <link href="/css/font-awesome.css" rel="stylesheet">
</head>
<body>
<div class="lock-holder">
    <div class="form-group pull-left input-username">
        <div class="input-group">
            <input type="text" class="form-control" id="uname" placeholder="输入账号">
	    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>  
        </div>
    </div>
    <div class="form-group pull-right input-password">
        <div class="input-group">
            <input type="password" class="form-control " placeholder="输入密码" id="pwd">
	    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>  
        </div>
    </div>
</div>
<div class="avatar">
    <img src="/image/yaya.png" alt="蘑菇街TT开源小组" style="background-color: white;height: 110px;padding: 5px 0px 0px 0px;">
</div>
<div class="submit">
    <button type="button" class="btn btn-success btn-submit">Login</button>
</div>
<script src="/js/jquery.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/bootstrap-progressbar.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('.btn-submit').click(function(e){
            $.ajax({
                type: "POST",
                url: "/ajax/login",
                data: {uname:$("#uname").val(), pwd:$("#pwd").val()},
                dataType: "json",
                success: function(data){
                    if(data.status)
                    {
                        $('.input-username,dot-left').addClass('animated fadeOutRight')
                        $('.input-password,dot-right').addClass('animated fadeOutLeft')
                        $('.btn-submit').addClass('animated fadeOutUp')
                        setTimeout(function () {
                                $('.avatar').addClass('avatar-top');
                                $('.submit').html('<div class="progress"><div class="progress-bar progress-bar-success" aria-valuetransitiongoal="100"></div></div>');
                                $('.progress .progress-bar').progressbar();
                            },
                            500);
                        setTimeout(function () {
                                window.location.href = data.url;
                            },
                            1500);
                    }else{
                        $('.alert').remove();
                        var prependHtml = '<div class="alert alert-danger" role="alert">登录失败,用户名或者密码不正确!</div>';
                        $("body").prepend(prependHtml);
                    }
                }
            });
        });
	//绑定回车事件
	$(document).keydown(function(e){
		if(e.keyCode == 13){
			$('.btn-submit').click();
		}
	});

    });
</script>
</body></html>

TT/protected/views/site/loginForm.php
<?php
/**
 * Project: yiiim
 * File: loginForm.php
 * User: 明心
 * Date: 14-8-5
 * Time: 上午11:28
 * Desc: 
 */

return array(
    'title'=>'Please provide your login credential',

    'elements'=>array(
        'uname'=>array(
            'type'=>'text',
            'maxlength'=>32,
        ),
        'pwd'=>array(
            'type'=>'password',
            'maxlength'=>32,
        ),
        'rme'=>array(
            'type'=>'checkbox',
        )
    ),

    'buttons'=>array(
        'login'=>array(
            'type'=>'submit',
            'label'=>'Login',
        ),
    ),
);